## Pre-commit setup
# See https://github.com/python-discord/code-jam-template/tree/main#pre-commit-run-linting-before-committing

# Make sure to edit the `additional_dependencies` list if you want to add plugins

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa

  - repo: local
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        name: isort (python)
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        minimum_pre_commit_version: '2.9.2'
        additional_dependencies: [ 'isort==5.10.1' ]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ '--max-line-length=88' ]
        additional_dependencies:
          - flake8-docstrings~=1.6.0

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
