name: build

on:
  push:
  pull_request:
    branches: [ main ]
    types: [ opened ]
concurrency: build-${{ github.sha }}

jobs:
  tests:
    env:
      DISPLAY: ':99.0'
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'collerek/cerebral-centaurs'
    strategy:
      matrix:
        python-version: [ "3.10" ]
      fail-fast: false

    steps:
      - name: Setup env
        run: |
          sudo apt-get update
          sudo apt-get -y install xvfb pulseaudio xsel
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python wheel support to speed up things
        run: pip install wheel

      # https://github.com/marketplace/actions/install-poetry-action
      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Poetry details
        run: |
          poetry --version
          poetry config --list

      - name: Install dependencies with poetry
        run: |
          poetry install --no-root
          poetry run python --version
          poetry show

      - name: Test with pytest
        run: poetry run pytest -vv --cov=codejam --cov=tests --cov-report=term-missing --cov-fail-under=100
