name: build

on:
  push:
  pull_request:
    branches: [ main ]
    types: [ opened ]
concurrency: build-${{ github.sha }}

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'collerek/cerebral-centaurs'
    strategy:
      matrix:
        python-version: [ "3.10" ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install poetry==1.1.11
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run tests
        run: poetry run pytest tests --cov=codejam --cov=tests --cov-report=term-missing --cov-fail-under=100
